name = "eat-what"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "eat-what-db"
database_id = "your-database-id-here"

# KV 存储配置 (用于缓存)
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

# 环境变量
[vars]
ENVIRONMENT = "production"
